### ISSUE TITLE
message receive does not receive messages

### ISSUE THREAD

**Issue by apleschu** [lmatte7/meshtastic-go#22]
Environment: raspberry pi native

Radio Settings: 
Radio Metadata
FirmwareVersion          2.3.9.f06c56a
DeviceStateVersion       22
CanShutdown              false
HasWifi                  true
HasBluetooth             false
HasEthernet              false
Role                     CLIENT
PositionFlags            811
HwModel                  PORTDUINO
HasRemoteHardware        false

meshtastic-go --port 127.0.0.1 message recv 

does not show messages received nor is it possible to trigger to a specific channel. 

Optional expanasion request: meshtastic-go --port 127.0.0.1 recv --index 6 --single

The above commandline should just receive a single line of text, output on STDOUT and exit then it can be used in shell scripts.

**Comment by Zappelphilipp** [comment]
just stumbled over this project because i am looking for a good CLI tool which i can use for my basestations to log incoming messages when i am not home.

can confirm, does not work and i agree with @apleschu : i also would use it as part of a script to be able to persist incoming messages. Also an optional "format" parameter which for example takes json would be awsome so the output can be parsed later on :D

**Comment by lmatte7** [comment]
PRs are always welcome! I'd be happy to review the code as well to give feedback.

If you'd prefer to wait a bit longer I can definitely look at adding those features. I'll do a bug fix release to get things working and then pack a few requested features into a following release. 

At most "persisting" messages would probably look like writing out to a file (which could work now if you sent the command to a file with the CLI). I could also add in a JSON output fairly easily since the commands are all based on protobufs anyway.

**Comment by lmatte7** [comment]
This has been fixed in the latest release. A new `json` parameter has also been added to the top level `info` command to output data in JSON and hopefully make things easier to parse in as part of a script
